<?xml version="1.0"?>
<package format="2">
  <name>hsr_openpi</name>
  <version>0.0.0</version>
  <description>The hsr_openpi package</description>

  <maintainer email="ookubo-takuya069@g.ecc.u-tokyo.ac.jp">Takuya Okubo</maintainer>

  <license>TODO</license>

  <buildtool_depend>catkin</buildtool_depend>
  <build_depend>geometry_msgs</build_depend>
  <build_depend>rospy</build_depend>
  <build_depend>sensor_msgs</build_depend>
  <build_export_depend>geometry_msgs</build_export_depend>
  <build_export_depend>rospy</build_export_depend>
  <build_export_depend>sensor_msgs</build_export_depend>
  <exec_depend>geometry_msgs</exec_depend>
  <exec_depend>rospy</exec_depend>
  <exec_depend>sensor_msgs</exec_depend>

  <export>
  </export>
</package>
